### ISSUE TITLE
Battery bug

### ISSUE THREAD

**Issue by Gordietm** [siavash79/AOSPMods#1]
Pixel 6 Pro
Android 12 QPR3 Beta 1
LSPosed v1.7.2-6455

All mods seem to work fine except for the Battery Style modification. When changing the battery style to circle or dash circle, a blank shows up in the status bar where the circle should be. Only the default setting for the battery works.

**Comment by siavash79** [comment]
Could you please be so kind and set it to circle, then reboot to see if it's still broken?

**Comment by Gordietm** [comment]
I set it to circle and rebooted. It's just an empty space where the battery
should be. I've attached a screenshot.

Gordie


Please excuse the brevity or spelling errors; this email was sent from a
mobile device.

**Comment by siavash79** [comment]
You're using an android version that I don't have installed on my devices yet to test.

If you had access to computer, and if you knew how to use adb, can you please run this command and send me the result?

adb shell su -c "logcat" | grep -i lspo

otherwise, I'll have to make one or two test versions to see which one works for you

**Comment by Gordietm** [comment]
I'm getting "grep" as not recognized.



Please excuse the brevity or spelling errors; this email was sent from a
mobile device.

**Comment by siavash79** [comment]
oops! sorry I forgot that you most likely are running it from windows.
try this one:

adb shell "su -c logcat | grep -i lspo"

**Comment by Gordietm** [comment]
Ok, it produced a whole log report, but how do I get it to send it to you?.
It's inside the PowerShell window and I can't seem to be able to copy and
paste it to an email



Please excuse the brevity or spelling errors; this email was sent from a
mobile device.

**Comment by siavash79** [comment]
Okay.... try this one:
open LSposed, go to logs (second icon from right) -> module logs -> press save button and send the file. (you can attach it to this reply from github website - not through email)

**Comment by Gordietm** [comment]
Please excuse the brevity or spelling errors; this email was sent from a
mobile device.

**Comment by siavash79** [comment]
unfortunately your attachments from Email don't get delivered. they have to be attached from website reply use this link to attach: (https://github.com/siavash79/AOSPMods/issues/1)

**Comment by Gordietm** [comment]
https://drive.google.com/file/d/14SNjBm1Ph9h6VNlFbVWSY8nPw1aLPmLn/view?usp=drivesdk

**Comment by Gordietm** [comment]
You should have access to the file now.

**Comment by siavash79** [comment]
There's no error reported in the logs.

That means that the source code of your ROM is (only slightly - otherwise I would see errors) different from the ones released by Google. (obviously: it's still beta version)

We will have to wait until Google releases the source code so that we can identify the problem. Nothing can be done at the moment

**Comment by siavash79** [comment]
Fixed on 1.0.0-canary-005
