### ISSUE TITLE
Few Things That On Aosp Mods That Don't Work As Intended

Sorry For Putting It All In One Ticket 😅
 

### ISSUE THREAD

**Issue by topsy-turvy99** [siavash79/AOSPMods#132]
OS: Lineage OS 19.1 A12.1

**Things That Dont Work:**

1)  **Enabling Network Monitor** doesn't work on my device,
Network Monitor already exists in my ROM, but it in the middle of the status bar, i can't move the position, so i was thinking AOSP Mod can help me achieve that, but sadly it doesn't work, hope it can be fixed.

2)  **Enabling Battery Bar** Does Nothing.

3)  **Status Bar Height** Doesn't Change The Size.

4)  Config Carrier Text On Lockscreen Doesn't Work.

**Bugs**

1)  Show No Of Unread Messages Works,But Its Not Placed Correctly, (Attaching The Screenshot Below), And it's Overlapped On Top Of the first notification icon, parts of covered icon is noticeable , which looks odd.
![Screenshot_20220508-164527_Pixel Launcher.png](https://user-images.githubusercontent.com/96917972/167293829-94fb7936-7206-4e36-93e6-26ec5043d822.png)

2)  **Vibrate On QS Tile Tap**, Is Very Low, Its hardly noticeable, it doesn't even respect the system level set strength, low/medium/high.

**Suggestions**

1)  Just a suggestion, i don't know if it's feasible, but can the features that are already built in the Rom, be disabled by default in AOSP Mods, so that they conflict with each other.

2)  Can You Please Add An Option To Reset To Default Setting Of AOSP Mods.

Thank You.

**Comment by siavash79** [comment]
Thanks

First of all, most of the mods that you mentioned as not working are inside statusbar. Since lineageOS has changed certain things in statusbar, the code is different from original AOSP and thus breaks the mod (you may have noticed that the mod is named AOSP mods). As mentioned, the compatibility and bugreport of the mod is measured based Stock Pixel ROM, which comes directly from Google.


Regarding vibration on QS, it's about to get better on next release.
Also, reset settings is in on the plans

Cheers

**Comment by topsy-turvy99** [comment]
Thank you for replying, i always considered Lineage As to be very closedto Stock AOSP, But yeah lineage almost have all the tweaks for status bar added in phone settings, i was only looking for a way to move the position of network speed meter but sadly i guess there's no workaround 😅

You can close the ticket.
