### ISSUE TITLE
Please add blur qs panel option... Is not laging and not consuming extra battery... Actually it is depend on processor capability

### ISSUE THREAD

**Issue by Avikbarui** [siavash79/AOSPMods#167]
Please add blur qs panel option... Is not laging and not consuming extra battery... Actually it is depend on processor capability

**Comment by EleoXDA** [comment]
If you ask any:
- MIUI user that used blur QS background
- Lineage user who has used ClearLineage mod

They will all say that it is lagging, causing high CPU usage, battery drain and also makes sure that AOSPMods always runs in background. Even worse than that is, this MOD will not work with power save turned on.

The reason is, to make blur bg, the mod needs to take screenshot of foreground, apply blur, and then put the image in background **every time you lower the QS page**. Every time. And yes, though this event depends on cpu and ram, it will get mixed results. And when it causes a millisecond of lag when lowering QS page, you will see tons of users complaining about lags while using AOSPMods.

And not only that, because this MOD requires AOSPMods to be always running in background, users will see it as if this MOD is causing battery drain.

So, no.
"_Is not laging and not consuming extra battery... Actually it is depend on processor capability_" is not a definitive or explanatory sentence. It is just merely a statement with zero proof.
