### ISSUE TITLE
Feature Request: Big QS Clocks?

### ISSUE THREAD

**Issue by raiyuulmao** [siavash79/AOSPMods#170]
### What's on your mind?
AhhHhh i think i have got another idea
how about adding big QS clocks?
Like kinda big clock instead of a small clock in the QS

### Is this feature implemented on any other app/mod/rom? please specify

We can see Big Qs Clock in these roms:
• Descendant OS
• AncientOS (If i remember you have to enable it from settings)
• Derpfest (Old builds had Big Qs clocks)
• Substratum themes???(Dunno honestly, have seen people adding Big QS clocks to their QS using substratum themes)

### Heres some pictures of the idea:

> ![IMG_20220521_181910_461](https://user-images.githubusercontent.com/45197348/169651324-170e0a80-3540-48e3-a0ea-ff059e225385.jpg)
> `ROM: DescendantOS`
> `<                                   `
> ![IMG_20220521_182053_751](https://user-images.githubusercontent.com/45197348/169651350-4159a031-132c-4615-84c4-17c32e72375a.jpg)
> `ROM: AncientOS`

**Comment by EleoXDA** [comment]
+1 the idea. Would love to implement this some time. I really liked the first screenshot. In pixel stock firmware we can see an empty space in both QS and QQS that could be used to implement this MOD. Just need to be sure to check how much free space is left when switching the font size and display size to the extremities so that the clock text does not get into other views on that screen.
![ZomboDroid 21052022200201.jpg](https://user-images.githubusercontent.com/27622683/169663837-5d8375ff-be65-4de0-8c62-1e675e66782c.jpg)

**Comment by wardii360** [comment]
![Screenshot_20220604-105501](https://user-images.githubusercontent.com/96117724/171970219-3bfab350-56e2-4a4a-ab2e-66c797932b8a.png)
![Screenshot_20220604-105730](https://user-images.githubusercontent.com/96117724/171970330-4617a449-f726-4b13-a3c0-9ddcaa3e4f3e.png)
 
Project Themer app in play store has a custom QS clock that looks very nice in my opinion. Works flawlessly on stock Pixel firmware. Not sure if they are looking to implement other designs though.

https://play.google.com/store/apps/details?id=com.drsants.eggproject

**Comment by EleoXDA** [comment]
Afaik project themer is not an open source app. So, without a source it would be hard to get it. With decompiling you lose a lot of information when no github source is available.

**Comment by wardii360** [comment]
Just mentioned it in case OP wanted to just install that instead of waiting for it to potentially added to this mod :)
