### ISSUE TITLE
Inactive QS tiles with wrong background color

### ISSUE THREAD

**Issue by mld9401** [siavash79/AOSPMods#181]
**Describe the bug**
QS tile's background uses wrong color in the last stable build. This issue was not present in the previous builds.

**Screenshots**
![Screenshot_20220527-122820_Lanceur d'applications Pixel.png](https://user-images.githubusercontent.com/15183134/170696085-a5b31409-3328-4c10-be99-4b0d0e418166.png)

How it should be look

![Screenshot_20220527-130455_Lanceur d'applications Pixel.png](https://user-images.githubusercontent.com/15183134/170696124-5a0b471b-0175-49f5-b1db-cfbac32e982e.png)

 - Device: POCO X3 NFC
 - OS: PixelExperience 12.1 (A12.1)

**Comment by siavash79** [comment]
Sometimes this happens. Well: only if you turn light QS tile option on and then off. Sometimes it doesn't correctly go back to dark theme. In such situations a systemUI restart will do the trick

**Comment by siavash79** [comment]
It was happening always. But because overlays were getting applied all the time you didn't see it. Now they are applied much less frequently in favor of speed and battery.

**Comment by mld9401** [comment]
Even if i restart th UI or the system the problem persists.

**Comment by EleoXDA** [comment]
It happens when you have repainter or any other themer app You need to force reload repainter after changing theme in AOSPMods as they can overlay over each other.
After you change theme in AOSPMods but not force applying in Repainter
![Screenshot_20220527-185630.png](https://user-images.githubusercontent.com/27622683/170744633-49622679-b190-407c-aa46-7fdd013ec2ef.png)

After you force apply in Repainter:
![Screenshot_20220527-185414.png](https://user-images.githubusercontent.com/27622683/170744748-574bd541-76a5-41ce-9d5f-1039dda70ea4.png)

**Comment by EleoXDA** [comment]
> I don't have any other themer app.

Do this:
Before disabling light QS Panel toggle, enable dual tone toggle, and then disable light QS toggle. Report back
