### ISSUE TITLE
Weird LTE+ icon after reset and uninstall.

### ISSUE THREAD

**Issue by widkit** [siavash79/AOSPMods#257]
I've recently used AOSP Mods and then uninstalled since it crashed SystemUI frequently.
I reset everything then uninstalled the module.
But my LTE+ icon seemed to change to something weird.
![Screenshot_20220628-130756_Pixel Launcher](https://user-images.githubusercontent.com/75989700/176156864-adb392e8-3a68-4662-9ce9-798bc04e4802.png)
My suspicion is that one of the iconpacks are still overwriting the default one.

**Comment by EleoXDA** [comment]
A magisk module cannot change any file after it is uninstalled from magisk manager

**Comment by widkit** [comment]
Probably It did change when it was installed. If that's the case. Might
actually not be the case after all.

**Comment by EleoXDA** [comment]
You don't understand.

Magisk module works like this:
1) if it is installed, while booting magisk is adding/replacing the files in system
2) if it is not installed, magisk doesn't change anything in system.

This happens in every boot and checks whether there is a installed module or not.

Just to be sure, you have to UNINSTALL the module, not UNCHECK in magisk manager. If you unchecked instead of UNINSTALL, then there still could be remnants of the module.

Your message says you uninstalled it. But this is just last check to get. If you really uninstalled, then your issue has nothing to do with this module.

**Comment by widkit** [comment]
I uninstalled it as I said, don't know what's wrong about it but I'm sure that AOSP Mods caused this issue. This issue happened to be appeared when I started using it.

**Comment by EleoXDA** [comment]
If you uninstalled the module then it is not related to this module. Since you haven't provided any other bugreport issue like logs and etc I cannot debug anymore.

But IF you uninstalled, then you should look elsewhere.
