### ISSUE TITLE
Feature request: Master switches that make hooking not happen

### ISSUE THREAD

**Issue by josephcsible** [siavash79/AOSPMods#26]
What's on your mind?
Currently, we always hook everything that we support, and the checks to actually change things happen inside of the hooks. I'd like to add master switches that can make hooking not happen at all in places where the user doesn't want to change anything.

Is this feature implemented on any other app/mod/rom? please specify
GravityBox works this way.

**Comment by siavash79** [comment]
The master switch is a good idea in terms of "compatibility". Meaning if one rom is not compatible with certain hooks, turning them off will let user at least use the other ones

What we have done in AOSPMods that is a bit different from Gravitybox is that we've separated the mods into different packages. So if some hook in one package fails, it won't affect the other packs

We need to keep in mind 2 things:
1. Users are not technical people and we can't expect them to understand the concept of hooking and such master switches
2. Users prefer to see their changes apply immediately. By using master switches we lose this option. But without it, at least we always have the "base" to apply things quickly in "most cases"

Finally: this conversation is not over: we really welcome continuing this discussion

**Comment by josephcsible** [comment]
You definitely make good points. A few thoughts:

> So if some hook in one package fails, it won't affect the other packs

My concern is that if there's an incompatibility, some of our hooks might break things rather than just cleanly failing completely.

> We need to keep in mind 2 things

How about this? Have all of the master switches default to "on", and only ever show them if you enable an "I am an advanced user" toggle. Then in cases where users don't like or understand them, they can just pretend they don't exist, and things will work exactly like they do today.

**Comment by siavash79** [comment]
Makes sense!

about the hooks that break things, we CAN implement in a way that they don't:
- If we gather the classes, methods, and even fields in advance (so if they are not there, they can break the mod package silently)

This way, we can handle incompatibilities to break cleanly. If you take a look into the Framework mods (like power torch), I did this practice, since I was really scared of bootloops (If they crash zygote, it's a certain bootloop). But I really didn't care about this that much on sysui mods (in favor of implementation speed at this stage)

Anyway: Your point about the advanced user section makes sense to me. Once we get to a more stable situation (in terms of users waiting for some important mods), we hopefully will start doing this

**Comment by siavash79** [comment]
I assigned BOTH of us to this case. Maybe you can have a hand in this feature as well

**Comment by siavash79** [comment]
This is probably what you're looking for:

https://github.com/siavash79/AOSPMods/blob/master/app/src/main/java/sh/siava/AOSPMods/systemui/QQSBrightness.java
