### ISSUE TITLE
SystemUi does not function on EvolutionX.

### ISSUE THREAD

**Issue by MirageSteezyBoi2** [siavash79/AOSPMods#309]
I believe this is due to the way AOSPMods opens with the settings icon. EvolutionX already uses that function to open "The Evolver" which is the ROM's customization suite.

**Comment by siavash79** [comment]
The mod isn't generally compatible with EvoX
Instead of the settings long press you can use the app shortcut

**Comment by dttzyjw0012** [comment]
I build my own PixelXpert version which I named it AospXpert for Android 12+ AOSP roms. yes, this is not for the GoogleOS(which I call the Google Pixel device's stock rom). So if u want to use my mod, pls go to my project: https://github.com/dttzyjw0012/AospXpert. And do not reply in this issus, i know the PixelXpert team do not to want to be disturbed.

to PixelXpert team: i reply this because i can not @ this issus auther or participants in my issus: https://github.com/siavash79/PixelXpert/issues/980 , but there are just 10 issus i will reply just like this, so i wish this would not disturb you, thx.
