### ISSUE TITLE
Flashlight toggle broken

### ISSUE THREAD

**Issue by askingforafriend2** [siavash79/AOSPMods#320]
On the latest Moto Edge 20 update the flashlight toggle is broken in the QS pannel, however it is able to be turned on through the chopping gesture. The toggle says that the camera is in use, although it isn't. I thought it might be relevant since the Motorola firmware is very close to Pixel.

**Comment by EleoXDA** [comment]
Unfortunately we cannot reproduce it on pixel stock firmware. Try pixel experience ROM. It is more near to pixel firmware and you will have near to zero difference

**Comment by dttzyjw0012** [comment]
I build my own PixelXpert version which I named it AospXpert for Android 12+ AOSP roms. yes, this is not for the GoogleOS(which I call the Google Pixel device's stock rom). So if u want to use my mod, pls go to my project: https://github.com/dttzyjw0012/AospXpert. And do not reply in this issus, i know the PixelXpert team do not be disturbed.

to PixelXpert team: i reply this because i can @ this issus auther or participants in my issus: #980 , but there are just 10 issus i will reply just like this, so i wish this would not disturb you, thx.

**Comment by dttzyjw0012** [comment]
I build my own PixelXpert version which I named it AospXpert for Android 12+ AOSP roms. yes, this is not for the GoogleOS(which I call the Google Pixel device's stock rom). So if u want to use my mod, pls go to my project: https://github.com/dttzyjw0012/AospXpert. And do not reply in this issus, i know the PixelXpert team do not to want to be disturbed.

to PixelXpert team: i reply this because i can not @ this issus auther or participants in my issus: https://github.com/siavash79/PixelXpert/issues/980 , but there are just 10 issus i will reply just like this, so i wish this would not disturb you, thx.
