### ISSUE TITLE
Ask to reapply dark theme color after boot

### ISSUE THREAD

**Issue by xslvrxslwt** [siavash79/AOSPMods#321]
As the tittle says, black color doesn't reapply on most of the custom ROMs after the reboot, so I think you should add a switch that's disabled by default and when user changes the option from (Default) to anything — show it.

**Comment by EleoXDA** [comment]
Theme color of AOSPMods is not supported fully. For better results use the repainter app by kdrag0n.

**Comment by xslvrxslwt** [comment]
> Theme color of AOSPMods is not supported fully. For better results use the repainter app by kdrag0n.

1. doesn't support non-gms ROMs (e.g. los microg)
2. doesn't have amoled black anyway?

**Comment by EleoXDA** [comment]
As was replied before:
- this MOD is built on pixel stock firmware to be used on ROMs that are similar to it (e.g. Pixel Experience).
- Theme options or issues are not topic of AOSPMods app as it works ok with pixel stock firmware. If you cannot use it on your custom ROM of your choice you can report it to your ROM dev/maintainer or use repainter app by kdrag0n.

**Comment by Jnss98b** [comment]
> doesn't have amoled black anyway?

![image](https://user-images.githubusercontent.com/24306400/185821122-ffe6e4a9-0206-4322-ae09-9f02f4ad8043.png)

**Comment by dttzyjw0012** [comment]
I build my own PixelXpert version which I named it AospXpert for Android 12+ AOSP roms. yes, this is not for the GoogleOS(which I call the Google Pixel device's stock rom). So if u want to use my mod, pls go to my project: https://github.com/dttzyjw0012/AospXpert. And do not reply in this issus, i know the PixelXpert team do not to want to be disturbed.

to PixelXpert team: i reply this because i can not @ this issus auther or participants in my issus: https://github.com/siavash79/PixelXpert/issues/980 , but there are just 10 issus i will reply just like this, so i wish this would not disturb you, thx.

**Comment by dttzyjw0012** [comment]
I build my own PixelXpert version which I named it AospXpert for Android 12+ AOSP roms. yes, this is not for the GoogleOS(which I call the Google Pixel device's stock rom). So if u want to use my mod, pls go to my project: https://github.com/dttzyjw0012/AospXpert. And do not reply in this issus, i know the PixelXpert team do not to want to be disturbed.

to PixelXpert team: i reply this because i can not @ this issus auther or participants in my issus: https://github.com/siavash79/PixelXpert/issues/980 , but there are just 10 issus i will reply just like this, so i wish this would not disturb you, thx.
