### ISSUE TITLE
AM/PM showing without even enabled

### ISSUE THREAD

**Issue by Yagami45** [siavash79/AOSPMods#327]
•Device - Redmi Note 7s
•Os - Android 12.1
•August 5th (Derpfest)
•Magisk Delta 129b509f-delta (2503)
•Magisk Modules - A12 Lockscreen Font (v1.0), AOSP Mods (v2.0.1), FastChargingNotZeeta (v3), G-visual Mod(v4.1), Hotello (Project Themer), Quickswitch (v3.3.1), Rboard Themes (v30), Substratum lite Overlay Helper (0.5.20) Shamiko (v0.5.2), Universal SafetyNet Fix (v2.3.1), Volte Rounded Font, Zygisk-Lsposed (v1.8.3(6594))
•Lsposed Version - v1.8.3 
•Lsposed Modules - AOSP Mods (v2.0.1), Core Patch (v3.8), Disable Flag Secure (v2.0.0), Killergram (v20.3.12), Lucky Patcher (v10.2.5), Mi Media Editor (v1.4), Themer (v1.2.1)

•Issue - The issue is that AM/PM is showing beside time in status bar even if it's not enabled. I've checked thoroughly in my device settings and also in the AOSP Mods app settings too. But, I didn't find anything similar which will enable that.
![Screenshot_20220825-002021_AOSP Mods](https://user-images.githubusercontent.com/97796717/186499797-938af060-7ef2-4ffd-8d73-608ac33f7066.png)
![Screenshot_20220825-002031_AOSP Mods](https://user-images.githubusercontent.com/97796717/186499803-682c6c1b-6208-4b6f-b600-1c2b7946b4e7.png)
![Screenshot_20220825-002054_Settings](https://user-images.githubusercontent.com/97796717/186499805-94da9de1-03de-40c3-b8c0-b3d41dc2db90.png)
![Screenshot_20220825-002108_Settings](https://user-images.githubusercontent.com/97796717/186499811-d8219be3-4bd3-4ac7-8b81-14261ea7c3b8.png)

**Comment by EleoXDA** [comment]
Sorry, you probably didn't read that bugreports from other ROMs are accepted only if those mentioned bugs are present in pixel stock firmware and pixel experience ROMs as well. This was just in start of bugreport text

**Comment by dttzyjw0012** [comment]
I build my own PixelXpert version which I named it AospXpert for Android 12+ AOSP roms. yes, this is not for the GoogleOS(which I call the Google Pixel device's stock rom). So if u want to use my mod, pls go to my project: https://github.com/dttzyjw0012/AospXpert. And do not reply in this issus, i know the PixelXpert team do not to want to be disturbed.

to PixelXpert team: i reply this because i can not @ this issus auther or participants in my issus: https://github.com/siavash79/PixelXpert/issues/980 , but there are just 10 issus i will reply just like this, so i wish this would not disturb you, thx.
