### ISSUE TITLE
 no flashlight while AOSPMods is activated [Bug] 

### ISSUE THREAD

**Issue by menotuu** [siavash79/AOSPMods#354]
### Describe the issue

while AOSPMods is activated, the flashlight cant be used, because the icon in the dropdown menu is deactivated.

### Steps to reproduce

when I uninstall AOSPMods the icon will be activated again.

![screenshot](https://user-images.githubusercontent.com/38182429/190617568-6b34e28b-3813-413f-a75c-59873a09202d.jpg)

### Expected bahavior

usable flashlight icon

### Your device setup (Please take some time to give correct information here)

LG V50 LM-V500N40b Android 12
Stock firmware
AOSPMods 2.1.0
Magisk 25101
LSPosed 1.8.4
API 93

correct, its not a no google pixel

with old versions its the same

### Logs

[LSPosed_2022-09-15T14_46_43.256.zip](https://github.com/siavash79/AOSPMods/files/9583187/LSPosed_2022-09-15T14_46_43.256.zip)

**Comment by siavash79** [comment]
It's a common symptom in many roms.

The module only registers to get notified about when the flashlight is on or off. Instead, ROM (by mistake) thinks the camera is being used, thus doesn't allow flashlight operations

The original SDK behavior is different: it understands that camera and flashlight are two different things and doesn't complicate everything

**Comment by dttzyjw0012** [comment]
I build my own PixelXpert version which I named it AospXpert for Android 12+ AOSP roms. yes, this is not for the GoogleOS(which I call the Google Pixel device's stock rom). So if u want to use my mod, pls go to my project: https://github.com/dttzyjw0012/AospXpert. And do not reply in this issus, i know the PixelXpert team do not to want to be disturbed.

to PixelXpert team: i reply this because i can not @ this issus auther or participants in my issus: https://github.com/siavash79/PixelXpert/issues/980 , but there are just 10 issus i will reply just like this, so i wish this would not disturb you, thx.
