### ISSUE TITLE
[Bug] Android 13 Taskbar is not showing up

### ISSUE THREAD

**Issue by erenmete** [siavash79/AOSPMods#367]
### Describe the issue

Stated in the title, gesture pill goes away but taskbar never shows up

### Steps to reproduce

Turned on the taskbar from navigation settings, restarted SystemUI, even rebooted the device.

### Expected bahavior

For taskbar to show up

### Your device setup (Please take some time to give correct information here)

Pixel Experience Unofficial Android 13 (No theming or customizations)
Poco F3
AOSPMods Full

### Logs

![Screenshot_20220924-032307](https://user-images.githubusercontent.com/58091473/192072079-b03c74b0-311f-40a6-915f-a2b6f0bd7b88.png)
![Screenshot_20220924-032341](https://user-images.githubusercontent.com/58091473/192072080-95398c13-37c7-4053-a193-1833be5a7bb0.png)

**Comment by EleoXDA** [comment]
Wait until ROM gets official. It is missing some parts to get official label. Once it gets, it will be fixed. Talk to your ROM dev. Every user on official 13 PE ROM can use taskbar now

**Comment by dttzyjw0012** [comment]
I build my own PixelXpert version which I named it AospXpert for Android 12+ AOSP roms. yes, this is not for the GoogleOS(which I call the Google Pixel device's stock rom). So if u want to use my mod, pls go to my project: https://github.com/dttzyjw0012/AospXpert. And do not reply in this issus, i know the PixelXpert team do not to want to be disturbed.

to PixelXpert team: i reply this because i can not @ this issus auther or participants in my issus: https://github.com/siavash79/PixelXpert/issues/980 , but there are just 10 issus i will reply just like this, so i wish this would not disturb you, thx.
