### ISSUE TITLE
[Bug] Flashlight tile not working

### ISSUE THREAD

**Issue by cybr47** [siavash79/AOSPMods#377]
### Describe the issue

Flashlight tile says Camera in use when AOSP Mods module is installed on A13 

### Steps to reproduce

1. Install LSposed 
2. Install AOSP Mods
3. Reboot
4. Check flashlight tile

### Expected bahavior

Flashlight tile should be working 

### Your device setup (Please take some time to give correct information here)

AOSPA-Topaz
Android 13 
September SPL
AOSP Mods 2.2.0

### Logs

#

> 
[LSPosed_2022-10-01T11_05_09.982779.zip](https://github.com/siavash79/AOSPMods/files/9690587/LSPosed_2022-10-01T11_05_09.982779.zip)
[LSPosed_2022-10-01T11_05_02.350410.zip](https://github.com/siavash79/AOSPMods/files/9690588/LSPosed_2022-10-01T11_05_02.350410.zip)

**Comment by EleoXDA** [comment]
Your custom ROM is not supported. It needs to be adjusted for AOSPMods to work properly. Please switch to one of the supported ROMs: Pixel Experience or Pixel Experience Plus. Pixel stock firmware for google pixel devices is also supported. Most other custom ROMs are also unofficially supported but some of them (like yours) are giving errors because of how developer of your ROM has changed the source code w.r.to AOSP source code. To find out which other custom ROMs are "unoffically" supported, please check out our telegram group and read messages from fellow members (>700 active members).

**Comment by cybr47** [comment]
Got it.  I mistakenly thought it was module side issue. Thanks for the clarification.👍
