### ISSUE TITLE
Vertical layout in QS

### ISSUE THREAD

**Issue by akmsk1999** [siavash79/AOSPMods#388]
What's on your mind?

Is this feature implemented on any other rom?
Yes-Evolution X(maybe cherishos too)

Vertical layout in quick settings...
If we use 3 QS columns...the titles of QS keeps scrolling from right-left... As there's less space

Evolution x or some other roms has this features
Titles are vertically placed below the QS tiles Icons
This way it looks much cleaner and appropriate
So,we cordially request u to implement this feature....

Thank you sir
![Screenshot_20221012-174736-01](https://user-images.githubusercontent.com/16622098/195336688-2793cc00-4f93-4312-9f22-bcf75c0135d6.jpeg)
![IMG_20221012_174456_783](https://user-images.githubusercontent.com/16622098/195336737-89d2c0a5-e681-4481-b758-9c342a29334c.jpg)

Ps.i know second screenshot has it all shabby....but this looks cool in both 2 column and 3 column QS tiles

**Comment by EleoXDA** [comment]
https://github.com/Evolution-X/packages_apps_Evolver/commit/a2a3de880fc7b59ccc1c6090bc0d2d788438319a

Commit link found by user

**Comment by siavash79** [comment]
However, I'm curious to know: What happens to QQS tiles in such mode?

**Comment by EleoXDA** [comment]
> However, I'm curious to know: What happens to QQS tiles in such mode?

I asked the same thing, they forwarded me a video with indian talk instead (https://www.youtube.com/watch?v=b8MiVaPosBs). I could take a low-res screenshot of how qqs looks like from that video:
![image](https://user-images.githubusercontent.com/27622683/195406202-581a1b11-6fc4-4c0d-932d-00665c82b1ac.png)

I guess there is zero documentation about it. Because when I searched for vertical qs or vertical qs ricedroid there were nothing related.

**Comment by akmsk1999** [comment]
Evox has this feature....even crdroid too(though it's not aosp)

**Comment by siavash79** [comment]
Implemented
