### ISSUE TITLE
Change some colors in pinch Black theme

### ISSUE THREAD

**Issue by bhaskar966** [siavash79/AOSPMods#43]
Pinch Black theme demo -
![Screenshot_20220408-144114_Pixel Launcher](https://user-images.githubusercontent.com/86063625/162405042-71581191-7518-4016-b264-90eca270859f.png)

Everything going full black ! It's awesome.
But if you can add some dim material you colors on the disabled toggles and on notification, it will be much better ( I personally like that).

Pinch Black + material you = Extraordinary theme 😅

Default Material You theme -
![Screenshot_20220408-144619_Chrome](https://user-images.githubusercontent.com/86063625/162405604-b129a4df-915c-4f44-8fc0-1aa1a4c15007.png)

**Comment by ElTifo** [comment]
Material You Colors are overwritten as soon as SystemUI is restarted or device reboots.

You can achieve a style similar to what you're asking if you restart SystemUI.

Pitch black theme with no SystemUI restart:

![Black_without_sysui_restart](https://user-images.githubusercontent.com/3270513/162425404-841f44a3-4792-451b-a323-5c5fffa08dd4.png)

Pitch black theme after a SystemUI restart:

![Black_with_sysui_restart](https://user-images.githubusercontent.com/3270513/162425508-d311653c-9912-47b6-8420-146c17872327.png)

This, in fact is an Android 12+ "limitation". The effect you really want can be achieved if you install kdrag0n's Repainter app. The dark themes on AOSP Mods aren't perfect since the overlays are overwritten by Monet system. Repainter, on the other hand, handles all that.

Cheers!

**Comment by bhaskar966** [comment]
![Screenshot_20220409-073611_Pixel Launcher](https://user-images.githubusercontent.com/86063625/162552524-d5d094a1-db0a-46fa-ab5c-32aee1316731.png)

I had the repainter app but I didn't use that for a long time...
Now I saw there are may new setting and features included !
Now it's looking cool thanks sir .
