### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by AISLVE** [siavash79/AOSPMods#498]
### Describe the issue

Brightness Slider broken on ArrowOS

### Steps to reproduce

1. Open AOSP Mods,do a bit of tinkering with QS Panel and the brightness slider will break.

### Your device setup (Please take some time to give correct information here)

Xiaomi Pad 5(Nabu)
Android 13 
No LSPOSED Modules
ArrowOS 08/12/22 build
Magisk Delta v25.2
No app except AOSP Mods and debloater

**Comment by EleoXDA** [comment]
Arrow os not supported. Bye

**Comment by dttzyjw0012** [comment]
I build my own PixelXpert version which I named it AospXpert for Android 12+ AOSP roms. yes, this is not for the GoogleOS(which I call the Google Pixel device's stock rom). So if u want to use my mod, pls go to my project: https://github.com/dttzyjw0012/AospXpert. And do not reply in this issus, i know the PixelXpert team do not to want to be disturbed.

to PixelXpert team: i reply this because i can not @ this issus auther or participants in my issus: https://github.com/siavash79/PixelXpert/issues/980 , but there are just 10 issus i will reply just like this, so i wish this would not disturb you, thx.
