### ISSUE TITLE
Disable Features when already included in the ROM

### ISSUE THREAD

**Issue by NAV-Management** [siavash79/AOSPMods#505]
I would like to have a way that certain things are not applied / adjusted.

Namely, in many AOSP ROMs, a battery icon customization is already present, but other features are missing that exist in the AOSP mods. And when I install the AOSP mods, every time the battery indicator is shown twice or the icon overwrites each other, which is quite annoying. Could also not find a workaround so far to turn that off to only use the battery icon customization from the ROM.

The same problems I have with the network speed indicator, when it's already included in the rom.

**Comment by EleoXDA** [comment]
You can easily do that by forking module and editing it. Currently only Pixel Experience and pixel stock firmware is supported. No other custom ROM/firmware is supported.

**Comment by dttzyjw0012** [comment]
I build my own PixelXpert version which I named it AospXpert for Android 12+ AOSP roms. yes, this is not for the GoogleOS(which I call the Google Pixel device's stock rom). So if u want to use my mod, pls go to my project: https://github.com/dttzyjw0012/AospXpert. And do not reply in this issus, i know the PixelXpert team do not to want to be disturbed.

to PixelXpert team: i reply this because i can not @ this issus auther or participants in my issus: https://github.com/siavash79/PixelXpert/issues/980 , but there are just 10 issus i will reply just like this, so i wish this would not disturb you, thx.
