### ISSUE TITLE
Brightness slider animation

### ISSUE THREAD

**Issue by AK2H** [siavash79/AOSPMods#508]
What's on your mind?
Add animation to the brightness slider when moving.

**Comment by EleoXDA** [comment]
It is not in scope right now.

**Comment by Jnss98b** [comment]
How is this not in scope when it's a bug?

**Comment by mingaldrichgan** [comment]
You're right, it's a bug. I think the problem is that the OP did not describe the bug properly, so it sounded like a feature request.

The bug is that, when you touch-and-drag along the brightness bar (in both collapsed and expanded QS views), the actual screen brightness does change with the finger's horizontal position, but the graphical representation of the brightness level does not change until you lift your finger.

**Comment by Jnss98b** [comment]
True. Hopefully this bug still gets fixed

**Comment by EleoXDA** [comment]
> True. Hopefully this bug still gets fixed

It was broken by Google firmware update. Let's hope they fix it in future firmware updates.
