### ISSUE TITLE
Feature Request: replace double click lock for camera with another app/flashlight

### ISSUE THREAD

**Issue by guyman624** [siavash79/AOSPMods#562]
What's on your mind?
I was hoping that I would be able to replace the double click for camera function on my phone with the flashlight. I recently installed Lineage which gave me the ability to hold for flashlight with the phone off, but I would much rather double click anywhere

It seems that most button remappers exclude the lock button from doing these types of things, so I was hoping a root would open that functionality.

Is this feature implemented on any other app/mod/rom? please specify
I'm not sure of any other roms that implement this.

**Comment by EleoXDA** [comment]
Lineage is a custom ROM that is not fully supported by AOSPMods (you can read in our GitHub ReadMe and telegram support group notes). Also, there is a function that can add flashlight on power button long press in lockscreen already in AOSPMods. Try it. If it doesn't work, then it is possibly because your custom ROM is not supported.
Additional remapping of power button is a security risk.
