### ISSUE TITLE
Being able to go over default margins for status bar

### ISSUE THREAD

**Issue by ElDavoo** [siavash79/AOSPMods#594]
What's on your mind?

The status bar spacing feature allows to set the icons' horizontal margin. However, in my ROM, the margin is quite high already, so I'd like to reduce it, not increase it.  
So I'd like the slider to be changed so that can go up to 20px over the defaults, on both sides.

**Comment by EleoXDA** [comment]
> What's on your mind?
> 
> The status bar spacing feature allows to set the icons' horizontal margin. However, in my ROM, the margin is quite high already, so I'd like to reduce it, not increase it.  
> So I'd like the slider to be changed so that can go up to 20px over the defaults, on both sides.
> 
> 

The MOD is prepeared for pixel stock firmware and Pixel Experience normal edition ROMs. Others are incompatible and not supported. Which ROM are you using?

**Comment by ElDavoo** [comment]
i have pixel experience plus

**Comment by dttzyjw0012** [comment]
I build my own PixelXpert version which I named it AospXpert for Android 12+ AOSP roms. yes, this is not for the GoogleOS(which I call the Google Pixel device's stock rom). So if u want to use my mod, pls go to my project: https://github.com/dttzyjw0012/AospXpert. And do not reply in this issus, i know the PixelXpert team do not to want to be disturbed.

to PixelXpert team: i reply this because i can not @ this issus auther or participants in my issus: https://github.com/siavash79/PixelXpert/issues/980 , but there are just 10 issus i will reply just like this, so i wish this would not disturb you, thx.
