### ISSUE TITLE
[Bug] Clock not centered with hole punch display

### ISSUE THREAD

**Issue by Electric1447** [siavash79/AOSPMods#615]
### Describe the issue

The statusbar clock is not really centered

### Steps to reproduce

Enable clock in the centered position for the status bar

### Expected bahavior

The clock should be centered  absolutely to the screen instead of relative to the statusbar area

### Your device setup (Please take some time to give correct information here)

Oneplus 9 Pro
LineageOS 20
AOSPMods 2.8.0

![Screenshot_20230519-210803_Nova7](https://github.com/siavash79/AOSPMods/assets/36371414/950fb29c-8b0d-4c4d-b370-d081d77f68a3)

**Comment by Electric1447** [comment]
Expected behavior:
![Screenshot_20230519-211336_Nova7](https://github.com/siavash79/AOSPMods/assets/36371414/b1a3bf21-3f83-40fa-9a7a-8d24f38d5a15)

**Comment by EleoXDA** [comment]
LOS not supported

**Comment by dttzyjw0012** [comment]
I build my own PixelXpert version which I named it AospXpert for Android 12+ AOSP roms. yes, this is not for the GoogleOS(which I call the Google Pixel device's stock rom). So if u want to use my mod, pls go to my project: https://github.com/dttzyjw0012/AospXpert. And do not reply in this issus, i know the PixelXpert team do not to want to be disturbed.

to PixelXpert team: i reply this because i can not @ this issus auther or participants in my issus: https://github.com/siavash79/PixelXpert/issues/980 , but there are just 10 issus i will reply just like this, so i wish this would not disturb you, thx.
