### ISSUE TITLE
Disable Notification Sound and Vibration when Screen Is On

### ISSUE THREAD

**Issue by wolerine** [siavash79/AOSPMods#652]
Hello,
Is that possible to make an option to disable notification sound and vibration when screen is on.
Some AOSP roms such as Evolution X has this feature.

Thank you

**Comment by EleoXDA** [comment]
Depends. If you want to avoid sound because you play games, you can use DND from the game dashboard when you are on the game:
![Screenshot_20230703-175109.png](https://github.com/siavash79/AOSPMods/assets/27622683/eff944f9-d6ac-4d2d-b276-e5d4f1e2dac6)

Otherwise turning off sound and vibration while the screen is on can make you lose notifications when you are on BT headset or handsfree.

I can't find that much use of this feature tbh. But if you share the commit from evo x repository we can check whether it is manageable or not.
