### ISSUE TITLE
[Bug] As I installed AOSP Mods, Zygisk becomes unavalible

### ISSUE THREAD

**Issue by Ximerixx** [siavash79/AOSPMods#669]
### Describe the issue

As I installed AOSP Mods, Zygisk becomes unavalible for some reason

### Steps to reproduce

1. Install AOSP mods through magisk module and reboot

### Expected bahavior

I expected it to work woth LSposed but that's impossible due to this bug

### Your device setup (Please take some time to give correct information here)

- Redmi Note 10 Pro (codename SWEET) 
- Android 13 (S)
- Pixel Experience (Plus edition) 
- Magisk version 26.1
- (screenshot included)
![photo_2_2023-07-30_23-47-14](https://github.com/siavash79/AOSPMods/assets/94797169/61d2e217-c248-4a60-b483-d50d134ac2ed)
- If I WILL enable aosp mods

![photo_1_2023-07-30_23-47-14](https://github.com/siavash79/AOSPMods/assets/94797169/60a7f401-f788-4a5d-aab2-33e69868ba0c)
- After disabling AOSP mods everything works as expected

- Just list of my modules
![photo_3_2023-07-30_23-47-14](https://github.com/siavash79/AOSPMods/assets/94797169/7febae24-18c7-4e36-844d-b5b4ad0b343d)

**Comment by EleoXDA** [comment]
You should enable zygisk in magisk manager. You should report this issue to LSPosed and your custom ROM dev. It could also have something to with Android 13 (S) version rather than standard Android 13.

As you might have read in bugreport windows, it says:
![image](https://github.com/siavash79/AOSPMods/assets/27622683/aef59025-6ca8-42a5-932f-43c23c806b89)

As PE+ is neither standard PE nor pixel stock firmware (i.e. not a supported ROM of AOSPMods) we can only suggest you to continue discussion in our telegram group https://t.me/AOSPMods_Support

Due to ROM incompatibility I will have to drop this bugreport

**Comment by Ximerixx** [comment]
lol 
k
isn't PE and PE+ _almost_ the same?

**Comment by EleoXDA** [comment]
> lol k isn't PE and PE+ _almost_ the same?

not even remotely

**Comment by dttzyjw0012** [comment]
I build my own PixelXpert version which I named it AospXpert for Android 12+ AOSP roms. yes, this is not for the GoogleOS(which I call the Google Pixel device's stock rom). So if u want to use my mod, pls go to my project: https://github.com/dttzyjw0012/AospXpert. And do not reply in this issus, i know the PixelXpert team do not to want to be disturbed.

to PixelXpert team: i reply this because i can not @ this issus auther or participants in my issus: https://github.com/siavash79/PixelXpert/issues/980 , but there are just 10 issus i will reply just like this, so i wish this would not disturb you, thx.
