### ISSUE TITLE
[Bug] Refreshes systemUI seemingly at random.

### ISSUE THREAD

**Issue by Spagett1** [siavash79/AOSPMods#694]
### Describe the issue

When scrolling the app it will randoml restart the systemUI.

### Steps to reproduce

Open app
Click on any module or scroll
SystemUI will restart sometime during use

### Expected bahavior

systemUI to only restart when toggling options.

### Your device setup (Please take some time to give correct information here)

Google pixel 4 running lineage OS (Android 13)
Magisk 26.1 
LSPosed Zygisk 1.9.1
AOSP Mods (Full version) 3.0.0

### Logs

[LSPosed_2023-09-06T18_03_08.650855.zip](https://github.com/siavash79/AOSPMods/files/12535250/LSPosed_2023-09-06T18_03_08.650855.zip)

The app can still be used but it refreshes the system ui when it shouldnt. I understand that this may not be taken into consideration as i am running lineageOS not stock or pixel experience so feel free to close this if it is out of scope.

**Comment by EleoXDA** [comment]
Los was never supported. Please read readme file

**Comment by Switch123456789** [comment]
From the Readme:
"This MOD is compatible with ROMs or firmware that are built based on fairly unmodified Android (AOSP) source code."
This applies to LOS more or less. Further down it says that some features might not work on ROMs like LOS.

To me that clearly indicates it is supported and only might lack some features. My phone became really unstable after updating and now I learn from a random bug-report it is was never meant to work with LOS in the first place. If LOS is not supported, I think you should state that clearly in the readme. Otherwise more people might mess up their phones and/or will make unnecessary bug-reports for LOS.

**Comment by EleoXDA** [comment]
> From the Readme:
> "This MOD is compatible with ROMs or firmware that are built based on fairly unmodified Android (AOSP) source code."
> This applies to LOS more or less. Further down it says that some features might not work on ROMs like LOS.
> 
> To me that clearly indicates it is supported and only might lack some features. My phone became really unstable after updating and now I learn from a random bug-report it is was never meant to work with LOS in the first place. If LOS is not supported, I think you should state that clearly in the readme. Otherwise more people might mess up their phones and/or will make unnecessary bug-reports for LOS.

Read it again!

![Screenshot_20230912-123403.png](https://github.com/siavash79/AOSPMods/assets/27622683/c7b48e7f-f12b-4f8c-959e-e76a52d30c57)

Here, I zoomed in for you

![Screenshot_20230912-123403~2.png](https://github.com/siavash79/AOSPMods/assets/27622683/e168cd82-898b-4855-9694-01386d6d7420)

ALWAYS read documentation before saying "I read it"

**Comment by Switch123456789** [comment]
In your screenshot it says: "it might not support all features" and I said in my comment "some features might not work".

It seems like you didn't read properly and here you are blaming the very same thing on me. The hypocrisy 😆

**Comment by dttzyjw0012** [comment]
I build my own PixelXpert version which I named it AospXpert for Android 12+ AOSP roms. yes, this is not for the GoogleOS(which I call the Google Pixel device's stock rom). So if u want to use my mod, pls go to my project: https://github.com/dttzyjw0012/AospXpert. And do not reply in this issus, i know the PixelXpert team do not to want to be disturbed.

to PixelXpert team: i reply this because i can not @ this issus auther or participants in my issus: https://github.com/siavash79/PixelXpert/issues/980 , but there are just 10 issus i will reply just like this, so i wish this would not disturb you, thx.
