### ISSUE TITLE
[Bug] Charging Information issue

### ISSUE THREAD

**Issue by Bruhipie** [siavash79/AOSPMods#696]
### Describe the issue

[This issue is similar to #648 but a bit more detailed]. So the thing is that, i have enabled "charging information on lock screen" and the information showed on lock screen is "not accurate". For example, when i connect my phone to the wall by using a power adapter, it shows "0.0 V, 0.0 W, 0.0 A” but shows correct "time required for full charge". But... when i connect my phone using USB Cable (like a laptop usb port), it displays a fixed value, i.e., "2.5 W, 0.5A, 5V", even when the actual charging speed is different (found out using Ampere). What i want to say is that, if it can show some random values, then why can't it show accurate values. i am ready to provide you any logs you may need. [I know PE+ is not supported but why not display accurate information when you can, right?]

### Steps to reproduce

1. Connect to wall
2. Get null values on lock screen
3. Connect phone to slow charging ports (usb port of laptop)
4. Get fixed values

### Expected bahavior

Show accurate values 

### Your device setup (Please take some time to give correct information here)

Device: Redmi Note 10T 5G (camellia)
Android Version: 13
Security Patch: August 2023 (Pixel Experience Plus, Build Date- 17/08/23)
Magisk: 26.3 (26300)
Magisk Modules: 
![Screenshot_20230912-191621_Sheeessh](https://github.com/siavash79/AOSPMods/assets/131473668/d9723895-393d-4422-bb68-088a2555e89d)
Apps with Superuser access: 
![Screenshot_20230912-191610_Sheeessh](https://github.com/siavash79/AOSPMods/assets/131473668/6282ef35-8a75-4193-825b-037dd1735485)
LSPosed Version: 1.9.1 (6990)
LSPosed Modules: AOSP Mods, Disable_FLAG_SECURE

**Comment by EleoXDA** [comment]
Custom ROM issue

**Comment by dttzyjw0012** [comment]
I build my own PixelXpert version which I named it AospXpert for Android 12+ AOSP roms. yes, this is not for the GoogleOS(which I call the Google Pixel device's stock rom). So if u want to use my mod, pls go to my project: https://github.com/dttzyjw0012/AospXpert. And do not reply in this issus, i know the PixelXpert team do not to want to be disturbed.

to PixelXpert team: i reply this because i can not @ this issus auther or participants in my issus: https://github.com/siavash79/PixelXpert/issues/980 , but there are just 10 issus i will reply just like this, so i wish this would not disturb you, thx.
