### ISSUE TITLE
[BUG] Can't hide VoLTE on AOSP Rom

### ISSUE THREAD

**Issue by PalmTamino** [siavash79/AOSPMods#702]
### Describe the issue

Theres no way for me to hide the VoLTE icon

### Steps to reproduce

Disable voLTE in AOSP Mods using my Rom, it won't work

### Expected behavior

it will hide the icon

### Your device setup (Please take some time to give correct information here)

Android 13 AOSP (Xperience Rom)
Xiaomi 12T Pro (diting)

LSPosed Info:
API version
100

Xposed API call protection
Enabled

Dex Optimizer Wrapper
Supported

Framework version
1.9.1 (6990)

Manager package name
com.android.shell

System version
13 (API 33)

Device
Xiaomi 22081212G 

System ABI

AOSP MODS 3.0.0 (APP VERSION)

**Comment by EleoXDA** [comment]
Incompatible custom ROM. Not supported

**Comment by dttzyjw0012** [comment]
I build my own PixelXpert version which I named it AospXpert for Android 12+ AOSP roms. yes, this is not for the GoogleOS(which I call the Google Pixel device's stock rom). So if u want to use my mod, pls go to my project: https://github.com/dttzyjw0012/AospXpert. And do not reply in this issus, i know the PixelXpert team do not to want to be disturbed.

to PixelXpert team: i reply this because i can not @ this issus auther or participants in my issus: https://github.com/siavash79/PixelXpert/issues/980 , but there are just 10 issus i will reply just like this, so i wish this would not disturb you, thx.
